<?php

namespace PruductBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function decrementer($id,$nbre)
    {
        $query = $this->getEntityManager()
            ->createQuery('UPDATE PruductBundle:Produit t SET t.quantite= :nb  WHERE t.id = :id');
        $query->setParameter('nb', $nbre);
        $query->setParameter('id', $id);
        // $query->setParameter('nvdate', new \DateTime());

        $query->execute();
    }

    public function incrementer($id,$nbre)
    {
        $query = $this->getEntityManager()
            ->createQuery(' UPDATE PruductBundle:Produit t SET t.quantite= :nb  WHERE t.id = :id');
        $query->setParameter('nb', $nbre);
        $query->setParameter('id', $id);
        // $query->setParameter('nvdate', new \DateTime());

        $query->execute();
    }

}
